# Generated by Django 4.0.5 on 2022-06-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_data', models.CharField(max_length=5000)),
            ],
        ),
    ]
