# Generated by Django 4.0.6 on 2022-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_userlec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlec',
            name='all_data',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
