# Generated by Django 4.0.6 on 2023-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_alter_userlec_all_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlec',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlec',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
