# Generated by Django 4.0.6 on 2023-03-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0004_userlec_create_time_userlec_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_img', models.FileField(upload_to='image/')),
            ],
        ),
    ]
